services:
  db:
    build: ./MariaDB
    restart: always
    container_name: maria_db
    env_file: ./MariaDB/.env.dev
    ports:
      - "3306:3306"
    # healthcheck:
    #   test: ["CMD", 'mariadb', 'ping', '-h', db, '-u', 'root', '-p$$MARIADB_ROOT_PASSWORD' ]
    #   interval: 3s
    #   retries: 5

  backend:
    build: ./HowlBack
    restart: always
    container_name: howl_back
    env_file: ./HowlBack/.env.dev
    # depends_on: 
    #   db:
    #     condition: service_healthy
    ports:
      - "8080:8080"
