services:
  db:
    build: ./MariaDB
    restart: always
    container_name: mariaDB
    env_file: ./MariaDB/.env.dev
    ports:
      - "3306:3306"
    healthcheck:
      # Check if an external user can connect to the TCP port of the MariaDB server
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect"]
      interval: 3s
      retries: 5

  backend:
    build: 
      context: .
      dockerfile: ./HowlBack/Dockerfile
    restart: always
    container_name: howlBack
    env_file: ./HowlBack/.env.dev
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build: 
      dockerfile: ./OfficeHowlers/Dockerfile
    restart: always
    container_name: officeHowlers
    ports:
      - "5173:5173"

  apacheshib:
    image: dockerhub.csc.ncsu.edu/ignacioxd/apacheshib-proxy
    ports:
      - 443:443
    volumes:
      - ./logs:/var/log/apache2
    environment:
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=5173
      - FRONTEND_PROTOCOL=http
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - BACKEND_PROTOCOL=http
      - LOGIN_PATH=/
      - SERVER_NAME=localhost


